---
# tasks file for compute
- name: Restart Compute Services
  service: name={{item}} state=restarted
  with_items:
    - nova-compute
    - neutron-linuxbridge-agent
 #   - neutron-dhcp-agent
 #   - neutron-metadata-agent
